variable "name" {}
variable "dc" {}
variable "network_name" {}
variable "cluster_name" {}
variable "datastore_name" {}
variable "template" {}
variable "cpu" {}
variable "mem" {}
variable "ipv4_addr" {}
variable "ipv4_mask" {}
variable "ipv4_gw" {}
